assign-prompt: "@issue-assigner claim"
assigned-comment: "This issue has been successfully assigned to you! 🚀"
issue-already-assigned: "You have already been assigned to this issue."
max-assignees: 1
max-assignees-reached: "Sorry, maximum limit for assignees in this issue has reached. Please check other issues or contact a maintainer."
max-issues-for-user: 1

unassign-prompt: "@issue-assigner abandon"
unassigned-comment: "You have been unassigned to this issue successfully."
issue-was-not-assigned: "You were not assigned to this issue."

issue-opener-not-owner: "Thank you for opening this issue. Maintainers will check and approve if seems to be useful."
issue-opener-is-owner: "Comment '@issue-assigner claim' to get this issue assigned or '@issue-assigner abandon' to get this issue unassigned."
